[context.branch-deploy]
  command = "npm run build:production"
  functions = ""
  publish = "dist/apps/remix-ide"
  environment = { NODE_VERSION = "14.17.6" }

[context.production]
  environment = { NODE_VERSION = "14.17.6" }

[build]
  command = "npm run build:production"
  functions = ""
  publish = "dist/apps/remix-ide"
  environment = { NODE_VERSION = "14.17.6" }

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
